[workspace]
resolver = "3"
members = [
    "data_types",
    "guessing_game",
    "hello_world",
    "hello_world_cargo",
    "variables",
    "structs",
    "enums", "slices", "tuples", "pattern_matching", "collections", "strings"]
